language: android
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-23
  - extra-android-support
  - extra-android-m2repository
  licenses:
  - ".+"
before_install:
- openssl aes-256-cbc -K $encrypted_fbdd1e2ae3f8_key -iv $encrypted_fbdd1e2ae3f8_iv -in streamprocessor/release-key.keystore.enc -out streamprocessor/release-key.keystore -d
- git clone https://github.com/MD2Korg/mCerebrum-Utilities.git /home/travis/build/MD2Korg/mCerebrum-Utilities
- git clone https://github.com/MD2Korg/mCerebrum-DataKitAPI.git /home/travis/build/MD2Korg/mCerebrum-DataKitAPI
- git clone https://github.com/MD2Korg/stream-processor.git /home/travis/build/MD2Korg/stream-processor
env:
  global:
  - secure: pngIRQ0j5kksWLWFpR55T4jckccBCfn+sBPY5+BTbUWW9yMhNErUH0B3jwOfAoNSHnjAsGgSruZ0YPpSwbiitdwmT9PPGTJKyWyUlGK18Bv0vIGuvfHd0HQXvc0buTtZjaQqK1eZKO5J1S4QS5H+j/RgQSinaMA4Knjqk44zmBua1KoX2BPHjfHlunC+YtL5TknDFII4GUr+IHm+KFphQ5Jknjt0bIsbPwuVjHQ3+u5zZpe+KubHegJsqyn7/LhdNM8p3HK5H25Ck/ojkniF6MQXNLpfJRLbCHCmi2Yxf+LmNYOsE18KZlpWR+aj+Co7NlwITeXjqizg+YhWWStQWKpbxV7pPagg8HLD/4hYDEDKmDxB7fhaRgkfRx4sda/gasJ/VrpV9mcNynjHjr1mCYoF0aCtq7jYjDKMREgbI3HbrkVcxbbZTXFuP/q6VjjIeOczDQpcDbzx4OMoBRWnAoxJXPwz6VHUs6Ix4fCTZWnmltnKee9CODETpDYEJhcOVGut8Y4Vc6h6OBwvJw2ccFSfxfTLXNOBcuqPeXi2SdsV4VtRHQj16PJLHgunt8hpLOV/oRpvVKEwOVppPSCCYaohSZwAg4NPAGfDf/QQaTrGj8KWp2VXL3HM3khRRIiniZO3OTAbOiTWwx2UsNHLpli1LC+pY2d6xXCg84QFx+k=
  - secure: m48tYEc/j5FZ9RpfTJ2d+Yfn1XRnc3RLlXT4McsOunALOXEouXKOtN8cxekGfosFwuQFzOx27aTO4KiPEDjYXzTkkUoHOP6Fweu2KiePRaib1a0DjUAiN4tIPBo8vOEUiMpEmC5CtkcYEs//KfO1S8fj5OOsx/EJqwJXc22mnt/MuCimQRMRTXoVpEEQUI6oHRbV/Pycg2CqFeDWKlXtG40HTFntR0uUqt0YeS3MbXcsub22wBvX0ias0EZmOGa0bkRkpc42ajpA7KtvqguEqZ+HEcFQ+nERqo5aUPmjjQtQ4PQ2V8hmIaIRT4DokYeOzmdoYqzGMuNqyGQ6Halu+lMIOrpFaEU64i26QNXSrSLw3KwoeEj8c5Z188lH4vF2NPEJwRIgT52bKHdBXrpUnhqhVNBysoIaUSZAyNalsvJGdXIqbNe8+63nnHK8ySRpkTKY/M8yIkamGhPFI9h7EspZ+vpKMmsjcjmjZa6xep5lFLSJJ3LQv+XEhew0EJG0NhsHn75yHxPm7LjcInJnc7/ILgRCV8cS/TBYRn+j9Lzmf5V+g0tVVdVTpVl9RH4yxo0MOWjCPBdIB9jy+VZ/nqvERd/0JhmYrdWCKDFND+axoFVpiv7Y51+ds0p1Icu/cs2HaHRdvsVyMhmZDFc3WlrrE4rU/vYCNAPWsER6yAM=
  - secure: AMXYV1SlYzCGYPhsQizcwGWF5aCcoSPlKWTec+YjBwet3/M54IKNUZ5+MKajhFxHC/4xPuwzdZ7uCI38Dhs3ToBO/dZDGlkrRrP+HNPCYagSN2qmGlarKTwXOGhLZD52wUke45Tkb9I3m4jb5nATXzurRBC2Srl3I7UgL3dW+m4NGhEn+mn5/lmZ/7u1WIdZjlNjBiD9FW9x6VmuOmaTaiZr6py5Xgd7J/SuOlfElCtl1OQTaEEEXVqb4lP+G59VZExsHCQxQYL0JOCZQ43xJF3i6CcKmHFiv4vT21XzoHPgpz4aH4IDQzYPn0OAhJda9p1CrHoCgECJs3qXrlzyzuVa84ymhwWelDe7Vb6jf/pbmKMXuFvHyJ0FE9lVMzJhKvYteOo+ho/df9HlHH9cfdOeDaG9R8hzJ0TG/0weyk7v7qmOUm9DO8/YLqhWnpOsPy3Awr4Zo+kL3mJ8f4wL5Je4wczkuSdkUTHAcqRkW4ovLICNsJftEHidhZVNKvPfy+dHGlcn3IzQxZ55vy0DojEHLS6ynzXOncHk7PHCoetYubNh8jgq720bitTfsKn9uB3YWwy81oGHQCgvpm3zkpwBFymog8RwnkVXA2KKUKSY6Sn3OBUfi1BRhhEsKitCW57U1uUHwje/0GzoHRw+Jr7HjhvV2WzNJjEQ6IqNyEw=
  - secure: OqI7cisTMpzPnuHyR3nHuSdh1KgDGVXELwLJTWMf34qrMXtGxQI+vL8u+oPQ4HzSFKFe9aus7i2oaO6Ik6/qnHjG1X2jyP3zbvYcX4RCeTG6Y2tgZ5w4eDBVy2S+M8tzMn6/DqBoR6AkqnqR/nBlF3mA6659e5idKp1Mut+rFzQfBTtnNYyGD6DJSHlYIbdK6pHkuSj0J4TXKUT9IsU3tL2bOs+GVOhEpe11oqMY5yytY4W/3TdLzlx82Z+1noCp/d+LxR9Wdf7fgT8SELt1cwP4/ImXi7nZPoPIAJCVVBUpmlmjKMQkJOVs3nz7j6fn5XnckPUIKWCMmEUS2ut4JyilpXmJV64QAvsnANQzexl4KlLyZCKyS7VSRI+auAkfs8FLB9DkK2073inDXU2FbqQgKi/a6/JubMzxdvlDJftX4eIaFjem5Drf5qx0EkdgWHCLc4is4BSQxVQ8CCWptYVEMy+KlXMx2ZrR6rLvLK81FRQkPf7+9mWCet6JSPc+sr05u+v7HHFstJjp7to+Hp8cZT7ipa9XwCOOyS1o6X5+n5RU6y+H9bkOzEwkltYzjDI/mhzy2ps3aHtxgPtlDWtls31XfTewf6l/78TDtKa46kkGr/nVpqdTULm5aBQNec6ZIpKxBkdOLl7cIlNPL1VJp3IltgZqs4KYLeAUVTA=
script:
- "./gradlew assembleRelease"
notifications:
  slack:
    secure: drSaLEsi+xlUePocfcDTLO9S/5XSBsnR6h7OzPhU4xsO+mBjH3qb93Qe4Jwzz9IZQ0UFzDcmu7ObHOksd6fDgvnIcmznowuABs7QFSF5dodF3eXuF/NJc5J3SqptrOZhlPhGQJcan8siBpLw5z+UBal9ORQPJ8e0SN2bxvRH30GzOlaBOrS0w9hGmtoIY/c8ZIjxGn7BK+b7qL6pNqD4tTg3BImh4Q8Q0icjlT/Pe4kq9pJuYP+Ph4B6THE5PY6W5kmaPSZT2wk72tbNa+1f0lxkO106+Fi4X/qEf6BNQ/2ufUi8cGyjYhu8ZRfGEQVwmwtk0goZvPRyxzHx94tc0/utmW+ZvEEdXOTfs1cE84xGvsYOmoMaMacJC0DPSRTJ269LnmUlTYZoZPyEaqEJp0vFLnS7ZwYcYBzEQ/coS1zKOEWX5a29ijvCOxeFGWF9NcEvaGfpoP/RiLJXjguKfrQLQiek+xkzmubSRWpP9LFoqtXwVMxle/zi/99Ry02nvmEUSK3BbAM57LBnrT+0lYDC/ocxTpQ3Gvd52qFoZBzb8Fshu2+3UYCSCHROkOdHtBmBvRKE4LiTz8/6xtzeL1n+1RSrbN13tbk01gkNIHagSLWUildtFkvok2pJXawslE88ZhRzOOK8ViWFenbhca6sPfvBebXccTJKnzi4GQc=
    on_success: change
    on_failure: always
    on_start: false
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: eLnvv4Sz2JrYwfWNz6tSRoZjIUSAEza92ZySq7nYMhtQp2syrC75ac3MSskTga7m9mdl0tI+AA0J9CbhyOZil6xGQFVy098xNdDPxhm53zG5aA/r0ToWe7fFBjWpKiPgF7aLK2iZzvq4+alsva3fOT+UYiTUD/PE8NenDsTzkKcfymvKOWrMKF+2H7nJaEfIPmv0cUm6SlSSmR3Wjh24DotYF1ejGSSF8TrAteuzv2bsuQBW75mVPSJvErGaOF+/xL1hQKUJPTowpGu0fsdP4B7xUxXwqKDJdwZC4+E4KeVwFdeeRRXEYED0H5QTO2vR0W6+Pq+GbMrH0FQ2frYw9teKlvqndAlI+VV+T53yPlJNdryOCNbAtFYTSGspFEkXc8f6/l2BeSnLXcBCI9WY5VGpG5U8OC3NL7nvNBa+vHPLZ/XSBWm/Xql0ntZZN6UfcU/d1Cz5a72SawZPhvoTXQXEqdBAARDmqBMQzTPqd3CZtFoIwajppWPeDH6AwK41to/qx9Ro6XU3qHWuH2mjBBgelLpz54pjHX2/HDrjld8UFWcx2FDhM/jaA6feyO64jp9sM1UMp3FMiYHEfB1i8DEwClHEFm9ItNni6q7fuDe/5wrYxGyNGCNucnRfEWIJulCkRMYPFbcYYfmCrm7Hgetzl91Tm/t+0wAgNZoKBsg=
  file: streamprocessor/build/outputs/apk/streamprocessor*.*.*.apk
  on:
    repo: MD2Korg/mCerebrum-StreamProcessor
    tags: true
  skip_cleanup: true
